name: build flow
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      
      - name: maven build
        run: mvn install

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: runt test on main branches
        run: mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle